### PR TITLE
Update NumPy pinning

### PR DESCRIPTION
**Pull request by xhochy**
Use the newer method that also allows for newly released versions of NumPy

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by marscher** [comment]
Thank you! Is the docs not up 2 date or are you enforcing a newer version of numpy?
https://conda-forge.org/docs/meta.html#building-against-numpy

The tests are failing in the last step with:
```

anaconda_upload is not set.  Not uploading wheels: []
+ upload_or_check_non_existence /recipe_root conda-forge --channel=main
Traceback (most recent call last):
  File "/opt/conda/bin/upload_or_check_non_existence", line 13, in <module>
    from binstar_client.utils import get_binstar
ImportError: cannot import name 'get_binstar'
```
This seems unrelated to the changes and I hope at least that merging it will succeed the building of the packages.

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
With the correct license family and updated NumPy pinning, the build now succeeds.

**Comment by marscher** [comment]
Thanks again!

**Pull request merged**
