### PR TITLE
Require java ?

### PR DESCRIPTION
**Pull request by jschueller**
It seems this package should require java, else we get this kind of errors (from https://github.com/conda-forge/staged-recipes/pull/21527):
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conda/staged-recipes/build_artifacts/mpxj_1670938130114/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.11/site-packages/jpype/_core.py", line 184, in startJVM
    jvmpath = getDefaultJVMPath()
              ^^^^^^^^^^^^^^^^^^^
  File "/home/conda/staged-recipes/build_artifacts/mpxj_1670938130114/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.11/site-packages/jpype/_jvmfinder.py", line 74, in getDefaultJVMPath
    return finder.get_jvm_path()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/staged-recipes/build_artifacts/mpxj_1670938130114/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.11/site-packages/jpype/_jvmfinder.py", line 212, in get_jvm_path
    raise JVMNotFoundException("No JVM shared library file ({0}) "
jpype._jvmfinder.JVMNotFoundException: No JVM shared library file (libjvm.so) found. Try setting up the JAVA_HOME environment variable properly.
```

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Review by marscher — COMMENTED** [review]
A JRE would be sufficient as runtime dependency. I'd not recommend dragging Java in at all to be honest. I know conda-forge has grown to like a mini-operating system, but that does not mean, users want to be forced to use every single component of it.

**Comment by jschueller** [comment]
is there a jre package ?

**Comment by marscher** [comment]
No, there is not.

**Pull request closed without merging**
