### PR TITLE
V1.4.0

### PR DESCRIPTION
**Pull request by marscher**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marscher** [comment]
@conda-forge-admin please rerender

**Comment by marscher** [comment]
This is just great... 
```ImportError: cannot import name 'itervalues' from 'conda.common.compat' (C:\Miniconda\lib\site-packages\conda\common\compat.py)```

**Comment by ctrueden** [comment]
It's a mismatch between `conda_build` and `conda`.

Bug was already reported upstream; see conda/conda-build#4481

Looks like https://github.com/conda/conda/commit/dedbb59ca01dd5448fc399e8987d02ece2817b52 removed `itervalues` (and a lot of other cruft) from `conda.common.compat`. It was included in conda 4.13.0. All that function did was:
```python
def itervalues(d, **kw):
    return iter(d.values(**kw))
```
So: can we downgrade to conda <4.13.0 for now? Or else wait for the conda-build fix to be released.

**Comment by marscher** [comment]
I think the conda build environment is kind of pinned inside the containers. So we would have to wait.

**Comment by marscher** [comment]
https://github.com/conda-forge/conda-build-feedstock/pull/176

**Comment by marscher** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
