### PR TITLE
Bump version to v0.7.5

### PR DESCRIPTION
**Pull request by khaeru**
I am working on conda-forge packages that require JPype1 > 0.7.4. v0.7.5 has been out on PyPI for nearly a month, but has not been updated in conda-forge, thus this PR.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by khaeru** [comment]
@conda-forge-admin, please rerender

**Comment by khaeru** [comment]
> Did you check the "Allow edits from maintainers" box?

I didn't see an option to do this.

**Comment by xhochy** [comment]
> > Did you check the "Allow edits from maintainers" box?
> 
> 
> 
> I didn't see an option to do this.

Probably because you pushed from a organization branch. There you cannot ue the bot. Please rerender locally using`conda smithy rerender`.

**Comment by khaeru** [comment]
> Probably because you pushed from a organization branch. There you cannot [use] the bot. Please rerender locally using `conda smithy rerender`.

Thanks for the explanation.

Since this isn't my recipe, and this was intended as a quick contribution, the several steps involved in [setting up Azure in order to run `rerender`](https://github.com/conda-forge/conda-smithy#making-a-new-feedstock) are too onerous. I'll close this PR and re-open a different one from a user repository.

**Pull request closed without merging**
